apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - manifests
  - storage
  - postgres
  - todo-app/manifests
  - todo-backend/manifests
  - nats/manifests
  - broadcaster/manifests
  - todo-cronjob/manifests
  - backup-cronjob/manifests

images:
  - name: todo-app
  - name: todo-backend
  - name: broadcaster
  - name: todo-reminder
  - name: postgres-backup
