apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- manifests
- storage
- postgres
- todo-app/manifests
- todo-backend/manifests
- nats/manifests
- broadcaster/manifests
- todo-cronjob/manifests
- backup-cronjob/manifests

images:
- name: broadcaster
  newName: broadcaster
  newTag: 7a6a091098dabdbca95ec2c6c64225982ff5c5b2
- name: postgres-backup
  newName: postgres-backup
  newTag: 7a6a091098dabdbca95ec2c6c64225982ff5c5b2
- name: todo-app
  newName: todo-app
  newTag: 7a6a091098dabdbca95ec2c6c64225982ff5c5b2
- name: todo-backend
  newName: todo-backend
  newTag: 7a6a091098dabdbca95ec2c6c64225982ff5c5b2
- name: todo-reminder
  newName: todo-reminder
  newTag: 7a6a091098dabdbca95ec2c6c64225982ff5c5b2
