apiVersion: v1
kind: ConfigMap

metadata:
  namespace: project
  name: broadcaster-config

data:
  NATS_URL: nats://nats-service:4222

  # Replace this value with the URL of the generic webhook receiver.
  WEBHOOK_URL: https://webhooksite.net/72b01015-205c-4eee-a143-7b1ce979d43e