apiVersion: batch/v1
kind: CronJob

metadata:
  name: todo-reminder

spec:
  schedule: "0 * * * *"

  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1

  jobTemplate:

    spec:
      ttlSecondsAfterFinished: 3600

      template:

        spec:

          restartPolicy: Never

          containers:

          - name: todo-reminder
            image: todo-reminder
            imagePullPolicy: Never

            env:

            - name: BACKEND_URL
              value: http://todo-backend-service

            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"

              limits:
                cpu: "200m"
                memory: "128Mi"