apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todo-images-claim
      containers:
        - name: todo-app
          image: todo-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: todo-app-config
                
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"
              
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/files