apiVersion: v1
kind: ConfigMap

metadata:
  namespace: project
  name: todo-app-config

data:

  PORT: "8080"

  TODO_BACKEND_URL: "http://todo-backend-service"

  IMAGE_URL: "https://picsum.photos/1200"

  IMAGE_CACHE_TIME: "600000"

  IMAGE_DIRECTORY: "/usr/src/app/files"