apiVersion: v1
kind: ConfigMap

metadata:
  namespace: project
  name: todo-backend-config

data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: todo_db
  NATS_URL: nats://nats-service:4222
