apiVersion: v1
kind: Service

metadata:
  namespace: project
  name: nats-service

spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
